name: Build Codebook

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-codebook:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebook source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get fonts
        run: make -C pdf fonts

      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: pdf/content.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          work_in_root_file_dir: true
          extra_system_packages: "ttf-inconsolata gcc g++"

      - name: Public
        run: |
          mkdir public
          cp pdf/codebook.pdf public

      - name: Publish Latex
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: public
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
